/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DragOverlay: typeof import('./components/DragOverlay.vue')['default']
    EditControls: typeof import('./components/EditControls.vue')['default']
    FileImporter: typeof import('./components/FileImporter.vue')['default']
    HelpDialog: typeof import('./components/HelpDialog.vue')['default']
    PhotoCarousel: typeof import('./components/PhotoCarousel.vue')['default']
    PhotoEditor: typeof import('./components/PhotoEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidePanel: typeof import('./components/SidePanel.vue')['default']
    TheToolbar: typeof import('./components/TheToolbar.vue')['default']
  }
}
